sudo: required
language: java
dist: bionic
jdk: openjdk8
python:
  - 3.8
  
addons:
  sonarcloud:
    organization: "oktayalizada"
    token: $SONAR_TOKEN

script:
  - ./mvnw clean install -B
  - mvn clean verify sonar:sonar -Pcoverage 
